name:
    weightOfEvidence

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.7
    - numpy=1.18.1
    - pandas=1.0.0
    - pytest=5.3.5
    - scikit-learn=0.23.1
    - scipy=1.4.1
    - seaborn=0.10.0
    - scikit-learn=0.23.1
    - jupyterlab=2.1.4
    - nb_black=1.0.7